# Generated by Django 5.2.15 on 2026-06-16 14:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True)),
                ('icon', models.CharField(default='fas fa-tag', max_length=50, verbose_name='آیکون')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='اسلاگ')),
                ('excerpt', models.TextField(max_length=500, verbose_name='خلاصه')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('author', models.CharField(default='دکتر سعید کریمی', max_length=100, verbose_name='نویسنده')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='تصویر')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='بازدید')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-published_at'],
            },
        ),
    ]
