# Generated by Django 5.2.15 on 2026-06-16 14:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان دوره')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('instructor', models.CharField(default='دکتر سعید کریمی', max_length=100, verbose_name='مدرس')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (تومان)')),
                ('duration_hours', models.PositiveIntegerField(verbose_name='مدت زمان (ساعت)')),
                ('level', models.CharField(choices=[('beginner', 'مبتدی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته')], default='beginner', max_length=20, verbose_name='سطح')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/', verbose_name='تصویر شاخص')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره\u200cها',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('expired', 'منقضی شده'), ('refunded', 'بازگشت وجه')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='یادآوری ارسال شد')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='دوره')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام',
                'verbose_name_plural': 'ثبت\u200cنام\u200cها',
                'ordering': ['-enrolled_at'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان جلسه')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب')),
                ('video_url', models.URLField(blank=True, verbose_name='لینک ویدیو')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='courses/videos/', verbose_name='فایل ویدیو')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات جلسه')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='مدت زمان (دقیقه)')),
                ('is_preview', models.BooleanField(default=False, verbose_name='پیش\u200cنمایش رایگان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'جلسه',
                'verbose_name_plural': 'جلسات',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ (تومان)')),
                ('status', models.CharField(choices=[('initiated', 'آغاز شده'), ('pending', 'در انتظار'), ('success', 'موفق'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='initiated', max_length=20, verbose_name='وضعیت')),
                ('authority', models.CharField(blank=True, max_length=255, verbose_name='کد مرجع درگاه')),
                ('ref_id', models.CharField(blank=True, max_length=255, verbose_name='شماره مرجع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='courses.enrollment', verbose_name='ثبت\u200cنام')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
